/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class ContinueWithVerificationUiFlow {
    /**
    * The ID of the verification flow
    */
    'id': string;
    /**
    * The URL of the verification flow
    */
    'url'?: string;
    /**
    * The address that should be verified in this flow
    */
    'verifiable_address': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "verifiable_address",
            "baseName": "verifiable_address",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContinueWithVerificationUiFlow.attributeTypeMap;
    }

    public constructor() {
    }
}

