/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Custom Hostname
*/
export class CustomDomain {
    'cookie_domain'?: string;
    'cors_allowed_origins'?: Array<string>;
    'cors_enabled'?: boolean;
    'created_at'?: Date;
    'custom_ui_base_url'?: string;
    'hostname'?: string;
    'id'?: string;
    'ssl_status'?: CustomDomainSslStatusEnum;
    'updated_at'?: Date;
    'verification_errors'?: Array<string>;
    'verification_status'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cookie_domain",
            "baseName": "cookie_domain",
            "type": "string",
            "format": ""
        },
        {
            "name": "cors_allowed_origins",
            "baseName": "cors_allowed_origins",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "cors_enabled",
            "baseName": "cors_enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "custom_ui_base_url",
            "baseName": "custom_ui_base_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "hostname",
            "baseName": "hostname",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "ssl_status",
            "baseName": "ssl_status",
            "type": "CustomDomainSslStatusEnum",
            "format": ""
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "verification_errors",
            "baseName": "verification_errors",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "verification_status",
            "baseName": "verification_status",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomDomain.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CustomDomainSslStatusEnum = "initializing" | "pending_validation" | "deleted" | "pending_issuance" | "pending_deployment" | "pending_deletion" | "pending_expiration" | "expired" | "active" | "initializing_timed_out" | "validation_timed_out" | "issuance_timed_out" | "deployment_timed_out" | "deletion_timed_out" | "pending_cleanup" | "staging_deployment" | "staging_active" | "deactivating" | "inactive" | "backup_issued" | "holding_deployment" | "" ;

