/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IdentityWithCredentialsOidcConfigProvider } from '../models/IdentityWithCredentialsOidcConfigProvider.ts';
import { IdentityWithCredentialsPasswordConfig } from '../models/IdentityWithCredentialsPasswordConfig.ts';
import { HttpFile } from '../http/http.ts';

export class IdentityWithCredentialsOidcConfig {
    'config'?: IdentityWithCredentialsPasswordConfig;
    /**
    * A list of OpenID Connect Providers
    */
    'providers'?: Array<IdentityWithCredentialsOidcConfigProvider>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "config",
            "baseName": "config",
            "type": "IdentityWithCredentialsPasswordConfig",
            "format": ""
        },
        {
            "name": "providers",
            "baseName": "providers",
            "type": "Array<IdentityWithCredentialsOidcConfigProvider>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IdentityWithCredentialsOidcConfig.attributeTypeMap;
    }

    public constructor() {
    }
}

