/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IdentityWithCredentialsOidc } from '../models/IdentityWithCredentialsOidc.ts';
import { IdentityWithCredentialsPassword } from '../models/IdentityWithCredentialsPassword.ts';
import { HttpFile } from '../http/http.ts';

/**
* Create Identity and Import Credentials
*/
export class IdentityWithCredentials {
    'oidc'?: IdentityWithCredentialsOidc;
    'password'?: IdentityWithCredentialsPassword;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "oidc",
            "baseName": "oidc",
            "type": "IdentityWithCredentialsOidc",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "IdentityWithCredentialsPassword",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IdentityWithCredentials.attributeTypeMap;
    }

    public constructor() {
    }
}

