/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Internal Provision Mock Subscription Request Body
*/
export class InternalProvisionMockSubscription {
    /**
    * Currency usd USD eur Euro
    */
    'currency': InternalProvisionMockSubscriptionCurrencyEnum;
    /**
    * Identity ID
    */
    'identity_id': string;
    /**
    * Billing Interval monthly Monthly yearly Yearly
    */
    'interval': InternalProvisionMockSubscriptionIntervalEnum;
    /**
    * Plan ID
    */
    'plan': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "InternalProvisionMockSubscriptionCurrencyEnum",
            "format": ""
        },
        {
            "name": "identity_id",
            "baseName": "identity_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "InternalProvisionMockSubscriptionIntervalEnum",
            "format": ""
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InternalProvisionMockSubscription.attributeTypeMap;
    }

    public constructor() {
    }
}


export type InternalProvisionMockSubscriptionCurrencyEnum = "usd" | "eur" ;
export type InternalProvisionMockSubscriptionIntervalEnum = "monthly" | "yearly" ;

