/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NormalizedProjectRevision } from '../models/NormalizedProjectRevision.ts';
import { HttpFile } from '../http/http.ts';

export class NormalizedProject {
    /**
    * The Project\'s Creation Date
    */
    'created_at': Date;
    'current_revision': NormalizedProjectRevision;
    'hosts': Array<string>;
    /**
    * The project\'s ID.
    */
    'id': string;
    /**
    * The project\'s slug
    */
    'slug': string;
    /**
    * The state of the project. running Running halted Halted deleted Deleted
    */
    'state': NormalizedProjectStateEnum;
    'subscription_id'?: string | null;
    /**
    * Last Time Project was Updated
    */
    'updated_at': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "current_revision",
            "baseName": "current_revision",
            "type": "NormalizedProjectRevision",
            "format": ""
        },
        {
            "name": "hosts",
            "baseName": "hosts",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "NormalizedProjectStateEnum",
            "format": ""
        },
        {
            "name": "subscription_id",
            "baseName": "subscription_id",
            "type": "string",
            "format": "uuid4"
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return NormalizedProject.attributeTypeMap;
    }

    public constructor() {
    }
}


export type NormalizedProjectStateEnum = "running" | "halted" | "deleted" ;

