/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Contains a redirect URL used to complete a login, consent, or logout request.
*/
export class OAuth2RedirectTo {
    /**
    * RedirectURL is the URL which you should redirect the user\'s browser to once the authentication process is completed.
    */
    'redirect_to': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "redirect_to",
            "baseName": "redirect_to",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OAuth2RedirectTo.attributeTypeMap;
    }

    public constructor() {
    }
}

