/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class ProjectApiKey {
    /**
    * The token\'s creation date
    */
    'created_at'?: Date;
    /**
    * The token\'s ID.
    */
    'id': string;
    /**
    * The Token\'s Name  Set this to help you remember, for example, where you use the token.
    */
    'name': string;
    /**
    * The token\'s owner
    */
    'owner_id': string;
    /**
    * The Token\'s Project ID
    */
    'project_id'?: string;
    /**
    * The token\'s last update date
    */
    'updated_at'?: Date;
    /**
    * The token\'s value
    */
    'value'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "owner_id",
            "baseName": "owner_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "project_id",
            "baseName": "project_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProjectApiKey.attributeTypeMap;
    }

    public constructor() {
    }
}

