/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectBrandingTheme } from '../models/ProjectBrandingTheme.ts';
import { HttpFile } from '../http/http.ts';

/**
* The Project Branding
*/
export class ProjectBranding {
    /**
    * The Customization Creation Date
    */
    'created_at': Date;
    'default_theme': ProjectBrandingTheme;
    /**
    * The customization ID.
    */
    'id': string;
    /**
    * The Project\'s ID this customization is associated with
    */
    'project_id': string;
    /**
    * The Project Branding Themes
    */
    'themes': Array<ProjectBrandingTheme>;
    /**
    * Last Time Branding was Updated
    */
    'updated_at': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "default_theme",
            "baseName": "default_theme",
            "type": "ProjectBrandingTheme",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "project_id",
            "baseName": "project_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "themes",
            "baseName": "themes",
            "type": "Array<ProjectBrandingTheme>",
            "format": ""
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return ProjectBranding.attributeTypeMap;
    }

    public constructor() {
    }
}

