/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Update Subscription Request Body
*/
export class UpdateSubscriptionBody {
    /**
    *  monthly Monthly yearly Yearly
    */
    'interval': UpdateSubscriptionBodyIntervalEnum;
    'plan': string;
    'return_to'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "interval",
            "baseName": "interval",
            "type": "UpdateSubscriptionBodyIntervalEnum",
            "format": ""
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "string",
            "format": ""
        },
        {
            "name": "return_to",
            "baseName": "return_to",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateSubscriptionBody.attributeTypeMap;
    }

    public constructor() {
    }
}


export type UpdateSubscriptionBodyIntervalEnum = "monthly" | "yearly" ;

