/* tslint:disable */
/* eslint-disable */
/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * The version of the OpenAPI document: v1.5.1
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type { PromiseMiddleware as Middleware } from './middleware.ts';
export { PromiseCourierApi as CourierApi,  PromiseFrontendApi as FrontendApi,  PromiseIdentityApi as IdentityApi,  PromiseJwkApi as JwkApi,  PromiseMetadataApi as MetadataApi,  PromiseOAuth2Api as OAuth2Api,  PromiseOidcApi as OidcApi,  PromisePermissionApi as PermissionApi,  PromiseProjectApi as ProjectApi,  PromiseRelationshipApi as RelationshipApi,  PromiseWellknownApi as WellknownApi } from './types/PromiseAPI.ts';

