/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Create Subscription Request Body
*/
export class CreateSubscriptionBody {
    /**
    *  usd USD eur Euro
    */
    'currency'?: CreateSubscriptionBodyCurrencyEnum;
    /**
    *  monthly Monthly yearly Yearly
    */
    'interval': CreateSubscriptionBodyIntervalEnum;
    'plan': string;
    'provision_first_project': string;
    'return_to'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "CreateSubscriptionBodyCurrencyEnum",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "CreateSubscriptionBodyIntervalEnum",
            "format": ""
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "string",
            "format": ""
        },
        {
            "name": "provision_first_project",
            "baseName": "provision_first_project",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "return_to",
            "baseName": "return_to",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateSubscriptionBody.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CreateSubscriptionBodyCurrencyEnum = "usd" | "eur" ;
export type CreateSubscriptionBodyIntervalEnum = "monthly" | "yearly" ;

