/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Error
*/
export class ErrorOAuth2 {
    /**
    * Error
    */
    'error'?: string;
    /**
    * Error Debug Information  Only available in dev mode.
    */
    'error_debug'?: string;
    /**
    * Error Description
    */
    'error_description'?: string;
    /**
    * Error Hint  Helps the user identify the error cause.
    */
    'error_hint'?: string;
    /**
    * HTTP Status Code
    */
    'status_code'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        },
        {
            "name": "error_debug",
            "baseName": "error_debug",
            "type": "string",
            "format": ""
        },
        {
            "name": "error_description",
            "baseName": "error_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "error_hint",
            "baseName": "error_hint",
            "type": "string",
            "format": ""
        },
        {
            "name": "status_code",
            "baseName": "status_code",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ErrorOAuth2.attributeTypeMap;
    }

    public constructor() {
    }
}

