/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GenericError } from '../models/GenericError.ts';
import { HttpFile } from '../http/http.ts';

export class NeedsPrivilegedSessionError {
    'error'?: GenericError;
    /**
    * Points to where to redirect the user to next.
    */
    'redirect_browser_to': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "GenericError",
            "format": ""
        },
        {
            "name": "redirect_browser_to",
            "baseName": "redirect_browser_to",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NeedsPrivilegedSessionError.attributeTypeMap;
    }

    public constructor() {
    }
}

