/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectServiceIdentity } from '../models/ProjectServiceIdentity.ts';
import { ProjectServiceOAuth2 } from '../models/ProjectServiceOAuth2.ts';
import { ProjectServicePermission } from '../models/ProjectServicePermission.ts';
import { HttpFile } from '../http/http.ts';

export class ProjectServices {
    'identity'?: ProjectServiceIdentity;
    'oauth2'?: ProjectServiceOAuth2;
    'permission'?: ProjectServicePermission;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "identity",
            "baseName": "identity",
            "type": "ProjectServiceIdentity",
            "format": ""
        },
        {
            "name": "oauth2",
            "baseName": "oauth2",
            "type": "ProjectServiceOAuth2",
            "format": ""
        },
        {
            "name": "permission",
            "baseName": "permission",
            "type": "ProjectServicePermission",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProjectServices.attributeTypeMap;
    }

    public constructor() {
    }
}

