/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubjectSet } from '../models/SubjectSet.ts';
import { HttpFile } from '../http/http.ts';

/**
* Relation Query
*/
export class RelationQuery {
    /**
    * Namespace to query
    */
    'namespace'?: string;
    /**
    * Object to query
    */
    'object'?: string;
    /**
    * Relation to query
    */
    'relation'?: string;
    /**
    * SubjectID to query  Either SubjectSet or SubjectID can be provided.
    */
    'subject_id'?: string;
    'subject_set'?: SubjectSet;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "namespace",
            "baseName": "namespace",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "relation",
            "baseName": "relation",
            "type": "string",
            "format": ""
        },
        {
            "name": "subject_id",
            "baseName": "subject_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "subject_set",
            "baseName": "subject_set",
            "type": "SubjectSet",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RelationQuery.attributeTypeMap;
    }

    public constructor() {
    }
}

