/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Set active project in the Ory Network Console Request Body
*/
export class SetActiveProjectInConsoleBody {
    /**
    * Project ID  The Project ID you want to set active.  format: uuid
    */
    'project_id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "project_id",
            "baseName": "project_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SetActiveProjectInConsoleBody.attributeTypeMap;
    }

    public constructor() {
    }
}

