/**
 * Ory APIs
 * Documentation for all public and administrative Ory APIs. Administrative APIs can only be accessed with a valid Personal Access Token. Public APIs are mostly used in browsers. 
 *
 * OpenAPI spec version: v1.1.39
 * Contact: support@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class SourcePosition {
    'Line'?: number;
    'column'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "Line",
            "baseName": "Line",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "column",
            "baseName": "column",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return SourcePosition.attributeTypeMap;
    }

    public constructor() {
    }
}

